name: Build docker images and publish to DockerHub

on:
  push:
    branches: [leo/master]
env:
  MOSQUITTO_VERSION_2: 2.0.18
  MOSQUITTO_VERSION_SUFFIX: -mosquitto_
  DOCKERFILE_MOSQUITTO_VERSION: 2.0.18
  DOCKERHUB_REPO: mosquitto-go-auth
jobs:
  mosq_2:
    name: Build and publish with Mosquitto version 2.x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get short git sha
        id: extract_sha
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            GITHUB_SHA="${{ github.event.pull_request.head.sha }}"
          fi
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      
      - name: Set Mosquitto version
        run: sed -i 's/ARG MOSQUITTO_VERSION=${{ env.DOCKERFILE_MOSQUITTO_VERSION }}/ARG MOSQUITTO_VERSION=${{ env.MOSQUITTO_VERSION_2 }}/' Dockerfile
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ steps.extract_sha.outputs.sha }}${{ format('{0}{1}', env.MOSQUITTO_VERSION_SUFFIX, env.MOSQUITTO_VERSION_2) }}
